#小技巧：项目中共有4份config.yaml,分别位于
#1、 根目录
#2、 /api
#3、 /microservice/helloworld/server
#4、 /microservice/helloworld/client
#在我的开发环境中，2-4 位置的 config.yaml是根目录下config.yaml的硬链接 (windows系统中 mklink /H命令，linux下ln命令)
#这样做的原因在于：
#1、因为很多package需要在import的时候就需要获得配置项，所以无法在程序启动时指定配置文件位置。config文件路径是硬编码的，与执行程序应在一个目录下
#2、用硬链接的方式，可以使整个项目只维护一份配置文件
#当然，可以直接复制多份config文件，但是这样管理起来就比较困难了

#数据库相关配置
DataBase:
  Connect:
    DBConnectString: goeasy:sNd%sLDjd*12@tcp(172.16.18.18:3306)/easy_workflow?charset=utf8mb4&parseTime=True&loc=Local
    MaxIdleConns: 10   #空闲连接池中连接的最大数量
    MaxOpenConns: 100  #打开数据库连接的最大数量
    ConnMaxLifetime: 3600  #连接可复用的最大时间（分钟）
  log:
    SlowThreshold: 1                 #慢SQL阈值(秒)
    LogLevel: 4                      #1:Silent  2:Error 3:Warn 4:Info
    IgnoreRecordNotFoundError: true  #忽略ErrRecordNotFound（记录未找到）错误 true|false
    Colorful: true                   #使用彩色打印 true|false
  NamingStrategy:
    TablePrefix:                     #表名前缀，如前缀为t_，则`User` 的表名应该是 `t_users`
    SingularTable: true              #使用单数表名，启用该选项，此时，`User` 的表名应该是 `user`

#GIN框架相关配置
Gin:
  GinMode: debug    # degug|release
  Port: :8180       #端口

#程序全局配置
App:
  LogPath: C:\Users\jk\go\src\easy-workflow\logs\      #日志文件路径
  UploadPath: C:\Users\jk\go\src\easy-workflow\logs\   #上传文件路径

